server:
  port: 8080

spring:
  application:
    name: application
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
      type: com.alibaba.druid.pool.DruidDataSource
    select:
      url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowMultiQueries=true
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true

  jackson:
    serialization:
      write-dates-as-timestamps: true

logging:
  level:
    com.application.*: debug

swagger:
  host: 192.168.0.1:8080/v1/jar

url:
  report: http://localhost:801/file/report/

terrain:
  sqlite:
    directory: D:\tmp\