server:
  port: 8081

spring:
  thymeleaf:
    mode: HTML
    cache: true
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    check-template-location: true
    template-resolver-order: 1

item:
  maps:
    12902:
      cn: "id,code,create_time,update_time"
      te: "task_group"
      we: " 1=1 "
