server:
  port: 9527

spring:
  application:
    name: demo-gateway
  cloud:
    gateway:
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: http://localhost:8081
          predicates:
            - Path=/demo/test/** # 断言，路径相匹配的进行路由
        - id: payment_route2
          uri: http://localhost:8081
          predicates:
            Path=/demo/test/** #断言,路径相匹配的进行路由
        - id: layer_1
          predicates:
            - Path=/layer/**
          uri: no://op
          filters:
            - UriHostPlaceholderFilter=10001
eureka:
  instance:
    hostname: localhost
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://demo:Demo2023@localhost:1001/eureka/
