server:
  port: 8081

spring:
  application:
    name: loadbalancer-feign-a

#eureka client
eureka:
  client:
    service-url:
      defaultZone: http://demo:Demo2023@localhost:1001/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
    lease-renewal-interval-in-seconds: 5 # 实例续期心跳间隔（默认30s），设置之后启动服务不需要等很久就可以访问到服务的内容
    lease-expiration-duration-in-seconds: 15 # 实例续期持续多久后失效（默认90s）

##feign参数优化
feign:
  client:
    config:
      # 这里用 default 就是全局配置，如果是写服务名称，则是针对某个服务的配置。
      default:
        # 日志级别（忽略大小写），包括：NONE（默认）、BASIC、HEADERS、FULL
        loggerLevel: FULL