server:
  port: 8082

spring:
  application:
    name: logback-feign-sleuth-b
  profiles:
    active: dev
  main:
    # 允许存在多个Feign调用相同Service的接口
    allow-bean-definition-overriding: true

#eureka client
eureka:
  client:
    service-url:
      defaultZone: http://demo:Demo2023@localhost:1001/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
    lease-renewal-interval-in-seconds: 5 # 实例续期心跳间隔（默认30s），设置之后启动服务不需要等很久就可以访问到服务的内容
    lease-expiration-duration-in-seconds: 15 # 实例续期持续多久后失效（默认90s）

mybatis:
  mapper-locations: "classpath:mapper/*.xml"

##feign参数优化
feign:
  client:
    config:
      # 这里用 default 就是全局配置，如果是写服务名称，则是针对某个服务的配置。
      default:
        loggerLevel: full
#  compression:
#    request:
#      enabled: true
#      mine-types: text/xml,application/xml,application/json
#      min-request-size: 2048
#    response:
#      enabled: true