server:
  port: 8081

spring:
  application:
    name: tlog-feign-a
  main:
    # 允许存在多个Feign调用相同Service的接口
    allow-bean-definition-overriding: true

#eureka client
eureka:
  client:
    service-url:
      defaultZone: http://demo:Demo2023@localhost:1001/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
    lease-renewal-interval-in-seconds: 5 # 实例续期心跳间隔（默认30s），设置之后启动服务不需要等很久就可以访问到服务的内容
    lease-expiration-duration-in-seconds: 15 # 实例续期持续多久后失效（默认90s）

tlog:
  # 自定义日志标签模板。（`$preApp`：上游微服务节点名称。`$spanId`：当前微服务节点的spanId。`$traceId`：当前微服务节点的traceId。）
  pattern: '<$preApp><$spanId><$traceId>'
  # 打印调用参数和时间
  enable-invoke-time-print: true